apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sirato-ingestion
  name: sirato-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sirato-ingestion
  strategy: {}
  template:
    metadata:
      labels:
        run: sirato-ingestion
    spec:
      containers:
        - env:
            - name: MONGO_CLIENT_URI
              value: mongodb://sirato-db:27017
            - name: MONGO_DB_NAME
              value: epirus
            - name: NODE_ENDPOINT
              value: {{NODE_ENDPOINT}}
            - name: DISPATCH_RATE
              value: {{DISPATCH_RATE}}
          image: web3labs/epirus-free-ingestion:latest
          name: ingestion
          resources: {}
      restartPolicy: Always
